"""Graph backend selection for RepoGraph."""

from __future__ import annotations

import os
from typing import Protocol

from .store import RepoGraph

DEFAULT_DB_BACKEND = "cog"
DEFAULT_DB_PATH = ".repograph"


class GraphStore(Protocol):
    def put_triple(self, subject: str, predicate: str, obj: str) -> None: ...
    def put_triples_batch(self, triples: list[tuple[str, str, str]]) -> None: ...
    def clear(self) -> None: ...
    def callers_of(self, symbol: str) -> list[str]: ...
    def callees_of(self, symbol: str) -> list[str]: ...
    def blast_radius(self, symbol: str, depth: int = 3) -> dict[str, list[str]]: ...
    def search(self, query: str, limit: int = 20) -> list[str]: ...
    def file_symbols(self, filepath: str) -> list[str]: ...
    def outgoing(self, symbol: str, predicate: str) -> list[str]: ...
    def incoming(self, symbol: str, predicate: str) -> list[str]: ...
    def first_outgoing(self, symbol: str, predicate: str) -> str | None: ...
    def has_symbol(self, symbol: str) -> bool: ...
    def stats(self) -> dict[str, int]: ...
    def load_metadata(self) -> dict[str, str | None]: ...
    def save_metadata(self, metadata: dict[str, str]) -> None: ...


def get_graph_store(
    *,
    backend: str | None = None,
    db_path: str | None = None,
) -> GraphStore:
    selected_backend = (backend or os.getenv("REPOGRAPH_DB_BACKEND", DEFAULT_DB_BACKEND)).lower()

    if selected_backend == "cog":
        return RepoGraph(db_path=db_path or os.getenv("REPOGRAPH_DB_PATH", DEFAULT_DB_PATH))

    raise ValueError(f"Unsupported graph backend: {selected_backend}")
